[32mINFO    [0m hhj:my_log.py:39 ====所有用例的前置操作：启动对戏APP(setUp)====
[32mINFO    [0m hhj:my_log.py:39 _______________D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Common\desired_caps.yaml_________________
[32mINFO    [0m hhj:my_log.py:39 <built-in method values of dict object at 0x00000272D8CACBC0>
[32mINFO    [0m hhj:my_log.py:39 <built-in method values of dict object at 0x00000272D8CACBC0>
[32mINFO    [0m hhj:my_log.py:39 ====每条用例的前置操作：启动对戏APP(setUpClass)====
[32mINFO    [0m hhj:my_log.py:39 _______________D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Common\desired_caps.yaml_________________
[32mINFO    [0m hhj:my_log.py:39 <built-in method values of dict object at 0x00000272D8C99C40>
[32mINFO    [0m hhj:my_log.py:39 <built-in method values of dict object at 0x00000272D8C99C40>
[32mINFO    [0m hhj:my_log.py:39 ****正常用例——查看用户协议****
[32mINFO    [0m hhj:my_log.py:39 引导页_查看用户协议等待元素('accessibility id', '《用户协议》')可见
[1m[31mERROR   [0m hhj:my_log.py:47 引导页_查看用户协议等待元素('accessibility id', '《用户协议》')可见失败！！！
Traceback (most recent call last):
  File "D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Common\base_page.py", line 37, in wait_ele_Visible
    WebDriverWait(self.driver, times, poll_frequency).until(EC.visibility_of_element_located(locator))
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "d:\python\python38\lib\site-packages\appium\webdriver\webdriver.py", line 279, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "d:\python\python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\python\python38\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "d:\python\python38\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "d:\python\python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'POST /element' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details
[32mINFO    [0m hhj:my_log.py:39 ====每条用例的后置操作：关闭对戏APP，清理环境(teardownClass)====