{"uuid": "94b0f01c-7bfa-4fc4-9868-219843d40b46", "children": ["7d1bf7cb-2407-4bc7-8b83-7765dabd9ab2"], "befores": [{"name": "start_function_App_and_launcher_name", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'D:\\\\Android\\\\android-sdk-windows\\\\platform-tools\\\\adb.exe -P 5037 -s e855dee1 install -g 'C:\\\\Program Files\\\\Appium Server GUI\\\\resources\\\\app\\\\node_modules\\\\appium\\\\node_modules\\\\io.appium.settings\\\\apks\\\\settings_apk-debug.apk'' exited with code 1'; Command output: adb: failed to install C:\\Program Files\\Appium Server GUI\\resources\\app\\node_modules\\appium\\node_modules\\io.appium.settings\\apks\\settings_apk-debug.apk: Security exception: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag\r\n\r\njava.lang.SecurityException: You need the android.permission.INSTALL_GRANT_RUNTIME_PERMISSIONS permission to use the PackageManager.INSTALL_GRANT_RUNTIME_PERMISSIONS flag\r\n\tat com.android.server.pm.PackageInstallerService.createSessionInternal(PackageInstallerService.java:601)\r\n\tat com.android.server.pm.PackageInstallerService.createSession(Package\n\n", "trace": "  File \"d:\\python\\python38\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python\\python38\\lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\JetBrains\\PyCharm\\PycharmProjects\\Duixi_Framework_V1\\TestCases\\Test0Welcome\\conftest.py\", line 58, in start_function_App_and_launcher_name\n    driver = baseDriver(automationName='uiautomator2',noReset=False)\n  File \"D:\\JetBrains\\PyCharm\\PycharmProjects\\Duixi_Framework_V1\\Common\\base_driver.py\", line 45, in baseDriver\n    driver = webdriver.Remote('http://127.0.0.1:{}/wd/hub'.format(server_port), caps)\n  File \"d:\\python\\python38\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 151, in __init__\n    super().__init__(\n  File \"d:\\python\\python38\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"d:\\python\\python38\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 225, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"d:\\python\\python38\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\python\\python38\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1649598565492, "stop": 1649598568535}], "start": 1649598565492, "stop": 1649598568607}