2022-04-07 23:30:10,245-INFO-my_log.py-hhj-日志信息：****开始获取系统Launcher名称****
2022-04-07 23:30:10,756-INFO-my_log.py-hhj-日志信息：****系统Launcher名称为.launcher3.Launcher****
2022-04-07 23:30:10,756-INFO-my_log.py-hhj-日志信息：****系统Launcher名称为.launcher3.Launcher****
2022-04-07 23:30:10,757-INFO-my_log.py-hhj-日志信息：====每条用例的前置操作：启动对戏APP(setUpClass)====
2022-04-07 23:30:10,757-INFO-my_log.py-hhj-日志信息：====每条用例的前置操作：启动对戏APP(setUpClass)====
2022-04-07 23:30:10,757-INFO-my_log.py-hhj-日志信息：====每条用例的前置操作：启动对戏APP(setUpClass)====
2022-04-07 23:30:10,759-INFO-my_log.py-hhj-日志信息：_______________D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Common\desired_caps.yaml_________________
2022-04-07 23:30:10,759-INFO-my_log.py-hhj-日志信息：_______________D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Common\desired_caps.yaml_________________
2022-04-07 23:30:10,759-INFO-my_log.py-hhj-日志信息：_______________D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Common\desired_caps.yaml_________________
2022-04-07 23:30:10,759-INFO-my_log.py-hhj-日志信息：_______________D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Common\desired_caps.yaml_________________
2022-04-07 23:30:10,762-INFO-my_log.py-hhj-日志信息：<built-in method values of dict object at 0x0000020EE7C131C0>
2022-04-07 23:30:10,762-INFO-my_log.py-hhj-日志信息：<built-in method values of dict object at 0x0000020EE7C131C0>
2022-04-07 23:30:10,762-INFO-my_log.py-hhj-日志信息：<built-in method values of dict object at 0x0000020EE7C131C0>
2022-04-07 23:30:10,762-INFO-my_log.py-hhj-日志信息：<built-in method values of dict object at 0x0000020EE7C131C0>
2022-04-07 23:30:10,762-INFO-my_log.py-hhj-日志信息：<built-in method values of dict object at 0x0000020EE7C131C0>
2022-04-07 23:30:11,273-INFO-my_log.py-hhj-日志信息：<built-in method values of dict object at 0x0000020EE7C131C0>
2022-04-07 23:30:11,273-INFO-my_log.py-hhj-日志信息：<built-in method values of dict object at 0x0000020EE7C131C0>
2022-04-07 23:30:11,273-INFO-my_log.py-hhj-日志信息：<built-in method values of dict object at 0x0000020EE7C131C0>
2022-04-07 23:30:11,273-INFO-my_log.py-hhj-日志信息：<built-in method values of dict object at 0x0000020EE7C131C0>
2022-04-07 23:30:11,273-INFO-my_log.py-hhj-日志信息：<built-in method values of dict object at 0x0000020EE7C131C0>
2022-04-07 23:30:11,273-INFO-my_log.py-hhj-日志信息：<built-in method values of dict object at 0x0000020EE7C131C0>
2022-04-07 23:30:24,363-INFO-my_log.py-hhj-日志信息：====每条用例的前置操作：启动对戏APP(setUpClass)====
2022-04-07 23:30:24,363-INFO-my_log.py-hhj-日志信息：====每条用例的前置操作：启动对戏APP(setUpClass)====
2022-04-07 23:30:24,363-INFO-my_log.py-hhj-日志信息：====每条用例的前置操作：启动对戏APP(setUpClass)====
2022-04-07 23:30:24,363-INFO-my_log.py-hhj-日志信息：====每条用例的前置操作：启动对戏APP(setUpClass)====
2022-04-07 23:30:24,363-INFO-my_log.py-hhj-日志信息：====每条用例的前置操作：启动对戏APP(setUpClass)====
2022-04-07 23:30:24,363-INFO-my_log.py-hhj-日志信息：====每条用例的前置操作：启动对戏APP(setUpClass)====
2022-04-07 23:30:24,363-INFO-my_log.py-hhj-日志信息：====每条用例的前置操作：启动对戏APP(setUpClass)====
2022-04-07 23:30:24,366-INFO-my_log.py-hhj-日志信息：_______________D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Common\desired_caps.yaml_________________
2022-04-07 23:30:24,366-INFO-my_log.py-hhj-日志信息：_______________D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Common\desired_caps.yaml_________________
2022-04-07 23:30:24,366-INFO-my_log.py-hhj-日志信息：_______________D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Common\desired_caps.yaml_________________
2022-04-07 23:30:24,366-INFO-my_log.py-hhj-日志信息：_______________D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Common\desired_caps.yaml_________________
2022-04-07 23:30:24,366-INFO-my_log.py-hhj-日志信息：_______________D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Common\desired_caps.yaml_________________
2022-04-07 23:30:24,366-INFO-my_log.py-hhj-日志信息：_______________D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Common\desired_caps.yaml_________________
2022-04-07 23:30:24,366-INFO-my_log.py-hhj-日志信息：_______________D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Common\desired_caps.yaml_________________
2022-04-07 23:30:24,366-INFO-my_log.py-hhj-日志信息：_______________D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Common\desired_caps.yaml_________________
2022-04-07 23:30:24,371-INFO-my_log.py-hhj-日志信息：<built-in method values of dict object at 0x0000020EE7BEAA80>
2022-04-07 23:30:24,371-INFO-my_log.py-hhj-日志信息：<built-in method values of dict object at 0x0000020EE7BEAA80>
2022-04-07 23:30:24,371-INFO-my_log.py-hhj-日志信息：<built-in method values of dict object at 0x0000020EE7BEAA80>
2022-04-07 23:30:24,371-INFO-my_log.py-hhj-日志信息：<built-in method values of dict object at 0x0000020EE7BEAA80>
2022-04-07 23:30:24,371-INFO-my_log.py-hhj-日志信息：<built-in method values of dict object at 0x0000020EE7BEAA80>
2022-04-07 23:30:24,371-INFO-my_log.py-hhj-日志信息：<built-in method values of dict object at 0x0000020EE7BEAA80>
2022-04-07 23:30:24,371-INFO-my_log.py-hhj-日志信息：<built-in method values of dict object at 0x0000020EE7BEAA80>
2022-04-07 23:30:24,371-INFO-my_log.py-hhj-日志信息：<built-in method values of dict object at 0x0000020EE7BEAA80>
2022-04-07 23:30:24,371-INFO-my_log.py-hhj-日志信息：<built-in method values of dict object at 0x0000020EE7BEAA80>
2022-04-07 23:30:25,122-INFO-my_log.py-hhj-日志信息：<built-in method values of dict object at 0x0000020EE7BEAA80>
2022-04-07 23:30:25,122-INFO-my_log.py-hhj-日志信息：<built-in method values of dict object at 0x0000020EE7BEAA80>
2022-04-07 23:30:25,122-INFO-my_log.py-hhj-日志信息：<built-in method values of dict object at 0x0000020EE7BEAA80>
2022-04-07 23:30:25,122-INFO-my_log.py-hhj-日志信息：<built-in method values of dict object at 0x0000020EE7BEAA80>
2022-04-07 23:30:25,122-INFO-my_log.py-hhj-日志信息：<built-in method values of dict object at 0x0000020EE7BEAA80>
2022-04-07 23:30:25,122-INFO-my_log.py-hhj-日志信息：<built-in method values of dict object at 0x0000020EE7BEAA80>
2022-04-07 23:30:25,122-INFO-my_log.py-hhj-日志信息：<built-in method values of dict object at 0x0000020EE7BEAA80>
2022-04-07 23:30:25,122-INFO-my_log.py-hhj-日志信息：<built-in method values of dict object at 0x0000020EE7BEAA80>
2022-04-07 23:30:25,122-INFO-my_log.py-hhj-日志信息：<built-in method values of dict object at 0x0000020EE7BEAA80>
2022-04-07 23:30:25,122-INFO-my_log.py-hhj-日志信息：<built-in method values of dict object at 0x0000020EE7BEAA80>
2022-04-07 23:30:40,512-INFO-my_log.py-hhj-日志信息：****引导页_温馨提示_退出应用_点击****
2022-04-07 23:30:40,512-INFO-my_log.py-hhj-日志信息：****引导页_温馨提示_退出应用_点击****
2022-04-07 23:30:40,512-INFO-my_log.py-hhj-日志信息：****引导页_温馨提示_退出应用_点击****
2022-04-07 23:30:40,512-INFO-my_log.py-hhj-日志信息：****引导页_温馨提示_退出应用_点击****
2022-04-07 23:30:40,512-INFO-my_log.py-hhj-日志信息：****引导页_温馨提示_退出应用_点击****
2022-04-07 23:30:40,512-INFO-my_log.py-hhj-日志信息：****引导页_温馨提示_退出应用_点击****
2022-04-07 23:30:40,512-INFO-my_log.py-hhj-日志信息：****引导页_温馨提示_退出应用_点击****
2022-04-07 23:30:40,512-INFO-my_log.py-hhj-日志信息：****引导页_温馨提示_退出应用_点击****
2022-04-07 23:30:40,512-INFO-my_log.py-hhj-日志信息：****引导页_温馨提示_退出应用_点击****
2022-04-07 23:30:40,512-INFO-my_log.py-hhj-日志信息：****引导页_温馨提示_退出应用_点击****
2022-04-07 23:30:40,512-INFO-my_log.py-hhj-日志信息：****引导页_温馨提示_退出应用_点击****
2022-04-07 23:30:43,517-INFO-my_log.py-hhj-日志信息：引导页_点击不同意按钮等待元素('accessibility id', '不同意')可见
2022-04-07 23:30:43,517-INFO-my_log.py-hhj-日志信息：引导页_点击不同意按钮等待元素('accessibility id', '不同意')可见
2022-04-07 23:30:43,517-INFO-my_log.py-hhj-日志信息：引导页_点击不同意按钮等待元素('accessibility id', '不同意')可见
2022-04-07 23:30:43,517-INFO-my_log.py-hhj-日志信息：引导页_点击不同意按钮等待元素('accessibility id', '不同意')可见
2022-04-07 23:30:43,517-INFO-my_log.py-hhj-日志信息：引导页_点击不同意按钮等待元素('accessibility id', '不同意')可见
2022-04-07 23:30:43,517-INFO-my_log.py-hhj-日志信息：引导页_点击不同意按钮等待元素('accessibility id', '不同意')可见
2022-04-07 23:30:43,517-INFO-my_log.py-hhj-日志信息：引导页_点击不同意按钮等待元素('accessibility id', '不同意')可见
2022-04-07 23:30:43,517-INFO-my_log.py-hhj-日志信息：引导页_点击不同意按钮等待元素('accessibility id', '不同意')可见
2022-04-07 23:30:43,517-INFO-my_log.py-hhj-日志信息：引导页_点击不同意按钮等待元素('accessibility id', '不同意')可见
2022-04-07 23:30:43,517-INFO-my_log.py-hhj-日志信息：引导页_点击不同意按钮等待元素('accessibility id', '不同意')可见
2022-04-07 23:30:43,517-INFO-my_log.py-hhj-日志信息：引导页_点击不同意按钮等待元素('accessibility id', '不同意')可见
2022-04-07 23:30:43,517-INFO-my_log.py-hhj-日志信息：引导页_点击不同意按钮等待元素('accessibility id', '不同意')可见
2022-04-07 23:30:43,529-ERROR-my_log.py-hhj-日志信息：引导页_点击不同意按钮等待元素('accessibility id', '不同意')可见失败！！！
Traceback (most recent call last):
  File "D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Common\base_page.py", line 37, in wait_ele_Visible
    WebDriverWait(self.driver, times, poll_frequency).until(EC.visibility_of_element_located(locator))
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "d:\python\python38\lib\site-packages\appium\webdriver\webdriver.py", line 279, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "d:\python\python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\python\python38\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "d:\python\python38\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "d:\python\python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'POST /element' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details

2022-04-07 23:30:43,529-ERROR-my_log.py-hhj-日志信息：引导页_点击不同意按钮等待元素('accessibility id', '不同意')可见失败！！！
Traceback (most recent call last):
  File "D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Common\base_page.py", line 37, in wait_ele_Visible
    WebDriverWait(self.driver, times, poll_frequency).until(EC.visibility_of_element_located(locator))
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "d:\python\python38\lib\site-packages\appium\webdriver\webdriver.py", line 279, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "d:\python\python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\python\python38\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "d:\python\python38\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "d:\python\python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'POST /element' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details

2022-04-07 23:30:43,529-ERROR-my_log.py-hhj-日志信息：引导页_点击不同意按钮等待元素('accessibility id', '不同意')可见失败！！！
Traceback (most recent call last):
  File "D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Common\base_page.py", line 37, in wait_ele_Visible
    WebDriverWait(self.driver, times, poll_frequency).until(EC.visibility_of_element_located(locator))
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "d:\python\python38\lib\site-packages\appium\webdriver\webdriver.py", line 279, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "d:\python\python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\python\python38\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "d:\python\python38\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "d:\python\python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'POST /element' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details

2022-04-07 23:30:43,529-ERROR-my_log.py-hhj-日志信息：引导页_点击不同意按钮等待元素('accessibility id', '不同意')可见失败！！！
Traceback (most recent call last):
  File "D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Common\base_page.py", line 37, in wait_ele_Visible
    WebDriverWait(self.driver, times, poll_frequency).until(EC.visibility_of_element_located(locator))
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "d:\python\python38\lib\site-packages\appium\webdriver\webdriver.py", line 279, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "d:\python\python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\python\python38\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "d:\python\python38\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "d:\python\python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'POST /element' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details

2022-04-07 23:30:43,529-ERROR-my_log.py-hhj-日志信息：引导页_点击不同意按钮等待元素('accessibility id', '不同意')可见失败！！！
Traceback (most recent call last):
  File "D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Common\base_page.py", line 37, in wait_ele_Visible
    WebDriverWait(self.driver, times, poll_frequency).until(EC.visibility_of_element_located(locator))
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "d:\python\python38\lib\site-packages\appium\webdriver\webdriver.py", line 279, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "d:\python\python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\python\python38\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "d:\python\python38\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "d:\python\python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'POST /element' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details

2022-04-07 23:30:43,529-ERROR-my_log.py-hhj-日志信息：引导页_点击不同意按钮等待元素('accessibility id', '不同意')可见失败！！！
Traceback (most recent call last):
  File "D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Common\base_page.py", line 37, in wait_ele_Visible
    WebDriverWait(self.driver, times, poll_frequency).until(EC.visibility_of_element_located(locator))
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "d:\python\python38\lib\site-packages\appium\webdriver\webdriver.py", line 279, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "d:\python\python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\python\python38\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "d:\python\python38\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "d:\python\python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'POST /element' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details

2022-04-07 23:30:43,529-ERROR-my_log.py-hhj-日志信息：引导页_点击不同意按钮等待元素('accessibility id', '不同意')可见失败！！！
Traceback (most recent call last):
  File "D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Common\base_page.py", line 37, in wait_ele_Visible
    WebDriverWait(self.driver, times, poll_frequency).until(EC.visibility_of_element_located(locator))
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "d:\python\python38\lib\site-packages\appium\webdriver\webdriver.py", line 279, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "d:\python\python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\python\python38\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "d:\python\python38\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "d:\python\python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'POST /element' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details

2022-04-07 23:30:43,529-ERROR-my_log.py-hhj-日志信息：引导页_点击不同意按钮等待元素('accessibility id', '不同意')可见失败！！！
Traceback (most recent call last):
  File "D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Common\base_page.py", line 37, in wait_ele_Visible
    WebDriverWait(self.driver, times, poll_frequency).until(EC.visibility_of_element_located(locator))
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "d:\python\python38\lib\site-packages\appium\webdriver\webdriver.py", line 279, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "d:\python\python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\python\python38\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "d:\python\python38\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "d:\python\python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'POST /element' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details

2022-04-07 23:30:43,529-ERROR-my_log.py-hhj-日志信息：引导页_点击不同意按钮等待元素('accessibility id', '不同意')可见失败！！！
Traceback (most recent call last):
  File "D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Common\base_page.py", line 37, in wait_ele_Visible
    WebDriverWait(self.driver, times, poll_frequency).until(EC.visibility_of_element_located(locator))
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "d:\python\python38\lib\site-packages\appium\webdriver\webdriver.py", line 279, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "d:\python\python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\python\python38\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "d:\python\python38\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "d:\python\python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'POST /element' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details

2022-04-07 23:30:43,529-ERROR-my_log.py-hhj-日志信息：引导页_点击不同意按钮等待元素('accessibility id', '不同意')可见失败！！！
Traceback (most recent call last):
  File "D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Common\base_page.py", line 37, in wait_ele_Visible
    WebDriverWait(self.driver, times, poll_frequency).until(EC.visibility_of_element_located(locator))
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "d:\python\python38\lib\site-packages\appium\webdriver\webdriver.py", line 279, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "d:\python\python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\python\python38\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "d:\python\python38\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "d:\python\python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'POST /element' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details

2022-04-07 23:30:43,529-ERROR-my_log.py-hhj-日志信息：引导页_点击不同意按钮等待元素('accessibility id', '不同意')可见失败！！！
Traceback (most recent call last):
  File "D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Common\base_page.py", line 37, in wait_ele_Visible
    WebDriverWait(self.driver, times, poll_frequency).until(EC.visibility_of_element_located(locator))
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "d:\python\python38\lib\site-packages\appium\webdriver\webdriver.py", line 279, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "d:\python\python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\python\python38\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "d:\python\python38\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "d:\python\python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'POST /element' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details

2022-04-07 23:30:43,529-ERROR-my_log.py-hhj-日志信息：引导页_点击不同意按钮等待元素('accessibility id', '不同意')可见失败！！！
Traceback (most recent call last):
  File "D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Common\base_page.py", line 37, in wait_ele_Visible
    WebDriverWait(self.driver, times, poll_frequency).until(EC.visibility_of_element_located(locator))
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "d:\python\python38\lib\site-packages\appium\webdriver\webdriver.py", line 279, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "d:\python\python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\python\python38\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "d:\python\python38\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "d:\python\python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'POST /element' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details

2022-04-07 23:30:43,529-ERROR-my_log.py-hhj-日志信息：引导页_点击不同意按钮等待元素('accessibility id', '不同意')可见失败！！！
Traceback (most recent call last):
  File "D:\JetBrains\PyCharm\PycharmProjects\Duixi_Framework_V1\Common\base_page.py", line 37, in wait_ele_Visible
    WebDriverWait(self.driver, times, poll_frequency).until(EC.visibility_of_element_located(locator))
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "d:\python\python38\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "d:\python\python38\lib\site-packages\appium\webdriver\webdriver.py", line 279, in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {
  File "d:\python\python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "d:\python\python38\lib\site-packages\appium\webdriver\errorhandler.py", line 31, in check_response
    raise wde
  File "d:\python\python38\lib\site-packages\appium\webdriver\errorhandler.py", line 26, in check_response
    super().check_response(response)
  File "d:\python\python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'POST /element' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details

2022-04-07 23:30:44,999-INFO-my_log.py-hhj-日志信息：====每条用例的后置操作：关闭对戏APP，清理环境(teardownClass)====
2022-04-07 23:30:44,999-INFO-my_log.py-hhj-日志信息：====每条用例的后置操作：关闭对戏APP，清理环境(teardownClass)====
2022-04-07 23:30:44,999-INFO-my_log.py-hhj-日志信息：====每条用例的后置操作：关闭对戏APP，清理环境(teardownClass)====
2022-04-07 23:30:44,999-INFO-my_log.py-hhj-日志信息：====每条用例的后置操作：关闭对戏APP，清理环境(teardownClass)====
2022-04-07 23:30:44,999-INFO-my_log.py-hhj-日志信息：====每条用例的后置操作：关闭对戏APP，清理环境(teardownClass)====
2022-04-07 23:30:44,999-INFO-my_log.py-hhj-日志信息：====每条用例的后置操作：关闭对戏APP，清理环境(teardownClass)====
2022-04-07 23:30:44,999-INFO-my_log.py-hhj-日志信息：====每条用例的后置操作：关闭对戏APP，清理环境(teardownClass)====
2022-04-07 23:30:44,999-INFO-my_log.py-hhj-日志信息：====每条用例的后置操作：关闭对戏APP，清理环境(teardownClass)====
2022-04-07 23:30:44,999-INFO-my_log.py-hhj-日志信息：====每条用例的后置操作：关闭对戏APP，清理环境(teardownClass)====
2022-04-07 23:30:44,999-INFO-my_log.py-hhj-日志信息：====每条用例的后置操作：关闭对戏APP，清理环境(teardownClass)====
2022-04-07 23:30:44,999-INFO-my_log.py-hhj-日志信息：====每条用例的后置操作：关闭对戏APP，清理环境(teardownClass)====
2022-04-07 23:30:44,999-INFO-my_log.py-hhj-日志信息：====每条用例的后置操作：关闭对戏APP，清理环境(teardownClass)====
2022-04-07 23:30:44,999-INFO-my_log.py-hhj-日志信息：====每条用例的后置操作：关闭对戏APP，清理环境(teardownClass)====
2022-04-07 23:30:44,999-INFO-my_log.py-hhj-日志信息：====每条用例的后置操作：关闭对戏APP，清理环境(teardownClass)====
2022-04-07 23:30:46,177-INFO-my_log.py-hhj-日志信息：====每条用例的后置操作：关闭对戏APP，清理环境(teardownClass)====
2022-04-07 23:30:46,177-INFO-my_log.py-hhj-日志信息：====每条用例的后置操作：关闭对戏APP，清理环境(teardownClass)====
2022-04-07 23:30:46,177-INFO-my_log.py-hhj-日志信息：====每条用例的后置操作：关闭对戏APP，清理环境(teardownClass)====
2022-04-07 23:30:46,177-INFO-my_log.py-hhj-日志信息：====每条用例的后置操作：关闭对戏APP，清理环境(teardownClass)====
2022-04-07 23:30:46,177-INFO-my_log.py-hhj-日志信息：====每条用例的后置操作：关闭对戏APP，清理环境(teardownClass)====
2022-04-07 23:30:46,177-INFO-my_log.py-hhj-日志信息：====每条用例的后置操作：关闭对戏APP，清理环境(teardownClass)====
2022-04-07 23:30:46,177-INFO-my_log.py-hhj-日志信息：====每条用例的后置操作：关闭对戏APP，清理环境(teardownClass)====
2022-04-07 23:30:46,177-INFO-my_log.py-hhj-日志信息：====每条用例的后置操作：关闭对戏APP，清理环境(teardownClass)====
2022-04-07 23:30:46,177-INFO-my_log.py-hhj-日志信息：====每条用例的后置操作：关闭对戏APP，清理环境(teardownClass)====
2022-04-07 23:30:46,177-INFO-my_log.py-hhj-日志信息：====每条用例的后置操作：关闭对戏APP，清理环境(teardownClass)====
2022-04-07 23:30:46,177-INFO-my_log.py-hhj-日志信息：====每条用例的后置操作：关闭对戏APP，清理环境(teardownClass)====
2022-04-07 23:30:46,177-INFO-my_log.py-hhj-日志信息：====每条用例的后置操作：关闭对戏APP，清理环境(teardownClass)====
2022-04-07 23:30:46,177-INFO-my_log.py-hhj-日志信息：====每条用例的后置操作：关闭对戏APP，清理环境(teardownClass)====
2022-04-07 23:30:46,177-INFO-my_log.py-hhj-日志信息：====每条用例的后置操作：关闭对戏APP，清理环境(teardownClass)====
2022-04-07 23:30:46,177-INFO-my_log.py-hhj-日志信息：====每条用例的后置操作：关闭对戏APP，清理环境(teardownClass)====
